PRAEMIEN_KATALOG = {
    1: {"name": "Döner Sandwich Beef", "cat": "doener-sandwich", "varianten": {"Classic":1000,"XXL":1250}},
    2: {"name": "Döner Sandwich Beef Cheese", "cat": "doener-sandwich", "varianten": {"Classic":1200,"XXL":1450}},
    3: {"name": "Döner Sandwich Chicken", "cat": "doener-sandwich", "varianten": {"Classic":800,"XXL":1000}},
    4: {"name": "Döner Sandwich Chicken Cheese", "cat": "doener-sandwich", "varianten": {"Classic":1000,"XXL":1200}},
    5: {"name": "Döner Sandwich Vegetarisch mit Käse", "cat": "doener-sandwich", "varianten": {"Classic":650,"XXL":800}},
    6: {"name": "Wrap Beef", "cat": "wrap-doener", "varianten": {"Classic":1000,"XXL":1250}},
    7: {"name": "Wrap Chicken", "cat": "wrap-doener", "varianten": {"Classic":800,"XXL":1000}},
    8: {"name": "Wrap Vegetarisch", "cat": "wrap-doener", "varianten": {"Classic":650,"XXL":800}},
    9: {"name": "Döner Teller Beef mit Pommes", "cat": "doener-teller", "varianten": {"Classic":1400,"XXL":1700}},
    10: {"name": "Döner Teller Beef mit Reis", "cat": "doener-teller", "varianten": {"Classic":1400,"XXL":1700}},
    11: {"name": "Döner Teller Chicken mit Pommes", "cat": "doener-teller", "varianten": {"Classic":1200,"XXL":1500}},
    12: {"name": "Döner Teller Chicken mit Reis", "cat": "doener-teller", "varianten": {"Classic":1200,"XXL":1500}},
    13: {"name": "Lahmacun Beef", "cat": "lahmacun", "varianten": {"Classic":1100,"XXL":1350}},
    14: {"name": "Lahmacun Chicken", "cat": "lahmacun", "varianten": {"Classic":900,"XXL":1100}},
    15: {"name": "Lahmacun Salat u. Käse", "cat": "lahmacun", "varianten": {"Classic":750,"XXL":950}},
    16: {"name": "Höhlen Salat", "cat": "salate", "varianten": {"":1050}},
    17: {"name": "Döner Salat", "cat": "salate", "varianten": {"":1050}},
    18: {"name": "Thunfisch Salat", "cat": "salate", "varianten": {"":1000}},
    19: {"name": "Gemischter Salat", "cat": "salate", "varianten": {"":950}},
    20: {"name": "Falafel Salat", "cat": "salate", "varianten": {"":1050}},
    21: {"name": "Beilagen Salat", "cat": "salate", "varianten": {"":400}},
    22: {"name": "Boxenstopp Beef", "cat": "boxenstopp", "varianten": {"Classic":850,"XXL":1100}},
    23: {"name": "Boxenstopp Chicken", "cat": "boxenstopp", "varianten": {"Classic":750,"XXL":1000}},
    24: {"name": "Boxenstopp Falafel", "cat": "boxenstopp", "varianten": {"Classic":850,"XXL":1100}},
    25: {"name": "Pommes", "cat": "boxenstopp", "varianten": {"Classic":400,"XXL":500}},
    26: {"name": "Portion Fleisch Beef", "cat": "boxenstopp", "varianten": {"Classic":950,"XXL":1150}},
    27: {"name": "Portion Fleisch Chicken", "cat": "boxenstopp", "varianten": {"Classic":850,"XXL":1050}},
    28: {"name": "Portion Reis", "cat": "boxenstopp", "varianten": {"Classic":600,"XXL":800}},
    29: {"name": "Falafel", "cat": "boxenstopp", "varianten": {"5 Stück":850,"8 Stück":1100}},
    30: {"name": "Bowl Beef mit Reis", "cat": "bowls", "varianten": {"":1450}},
    31: {"name": "Bowl Beef mit Pommes", "cat": "bowls", "varianten": {"":1450}},
    32: {"name": "Bowl Chicken mit Reis", "cat": "bowls", "varianten": {"":1250}},
    33: {"name": "Bowl Chicken mit Pommes", "cat": "bowls", "varianten": {"":1250}},
    34: {"name": "Bowl Falafel mit Reis", "cat": "bowls", "varianten": {"":1250}},
    35: {"name": "Bowl Falafel mit Pommes", "cat": "bowls", "varianten": {"":1250}},
    36: {"name": "Falafel Sandwich", "cat": "falafel", "varianten": {"Classic":850,"XXL":1050}},
    37: {"name": "Falafel Wrap", "cat": "falafel", "varianten": {"Classic":850,"XXL":1050}},
    38: {"name": "Falafel Lahmacun", "cat": "falafel", "varianten": {"Classic":900,"XXL":1100}},
    39: {"name": "Falafel", "cat": "falafel", "varianten": {"5 Stück":600,"8 Stück":900}},
    40: {"name": "Falafel Teller mit Pommes", "cat": "falafel", "varianten": {"Classic":1150,"XXL":1350}},
    41: {"name": "Falafel Teller mit Reis", "cat": "falafel", "varianten": {"Classic":1150,"XXL":1350}},
    42: {"name": "Falafel Box mit Pommes", "cat": "falafel", "varianten": {"Classic":850,"XXL":1050}},
    43: {"name": "Falafel Box mit Reis", "cat": "falafel", "varianten": {"Classic":850,"XXL":1050}},
    44: {"name": "Falafel Salat", "cat": "falafel", "varianten": {"":1050}},
    45: {"name": "Sucuk Sandwich", "cat": "alaturka", "varianten": {"Classic":900,"XXL":1100}},
    46: {"name": "Döner Burger Beef", "cat": "alaturka", "varianten": {"Classic":900,"XXL":1100}},
    47: {"name": "Döner Burger Chicken", "cat": "alaturka", "varianten": {"Classic":750,"XXL":950}},
    48: {"name": "Börek Sticks", "cat": "alaturka", "varianten": {"1 Stück":150,"5 Stück":600}},
    49: {"name": "Pide Hackfleisch", "cat": "pide", "varianten": {"Classic":1150,"XXL":1550}},
    50: {"name": "Pide Spinat", "cat": "pide", "varianten": {"Classic":1050,"XXL":1550}},
    51: {"name": "Pide Weichkäse", "cat": "pide", "varianten": {"Classic":1050,"XXL":1550}},
    52: {"name": "Pide Sucuk Knoblauchwurst", "cat": "pide", "varianten": {"Classic":1100,"XXL":1600}},
    53: {"name": "Pide Gemischt", "cat": "pide", "varianten": {"Classic":1200,"XXL":1700}},
    54: {"name": "Chicken Nuggets", "cat": "fingerfood", "varianten": {"6 Stück":550,"9 Stück":750,"20 Stück":1200}},
    55: {"name": "Chili Cheese Nuggets", "cat": "fingerfood", "varianten": {"6 Stück":750,"9 Stück":950,"20 Stück":1450}},
    56: {"name": "Mozzarella Sticks", "cat": "fingerfood", "varianten": {"6 Stück":800,"9 Stück":1000,"20 Stück":1450}},
    57: {"name": "Katmer Beef", "cat": "katmer", "varianten": {"Classic":1200,"XXL":1500}},
    58: {"name": "Katmer Chicken", "cat": "katmer", "varianten": {"Classic":1000,"XXL":1300}},
    59: {"name": "Beef Wrap", "cat": "kids", "varianten": {"":650}},
    60: {"name": "Chicken Wrap", "cat": "kids", "varianten": {"":550}},
    61: {"name": "Beef Box", "cat": "kids", "varianten": {"":650}},
    62: {"name": "Chicken Box", "cat": "kids", "varianten": {"":550}},
    63: {"name": "Nugget Box", "cat": "kids", "varianten": {"":550}},
    64: {"name": "Brot mit Soße", "cat": "kids", "varianten": {"":200}},
    65: {"name": "Pizza Margherita", "cat": "pizza", "varianten": {"Classic 32 cm":800,"XXL 40 cm":1300}},
    66: {"name": "Pizza Rindersalami", "cat": "pizza", "varianten": {"Classic 32 cm":950,"XXL 40 cm":1450}},
    67: {"name": "Pizza Truthan", "cat": "pizza", "varianten": {"Classic 32 cm":950,"XXL 40 cm":1450}},
    68: {"name": "Pizza Peperoniwurst", "cat": "pizza", "varianten": {"Classic 32 cm":950,"XXL 40 cm":1450}},
    69: {"name": "Pizza Pilze", "cat": "pizza", "varianten": {"Classic 32 cm":950,"XXL 40 cm":1450}},
    70: {"name": "Pizza Spinat", "cat": "pizza", "varianten": {"Classic 32 cm":1000,"XXL 40 cm":1500}},
    71: {"name": "Pizza Mozzarella", "cat": "pizza", "varianten": {"Classic 32 cm":1000,"XXL 40 cm":1500}},
    72: {"name": "Pizza Sucuk", "cat": "pizza", "varianten": {"Classic 32 cm":1100,"XXL 40 cm":1600}},
    73: {"name": "Pizza Milano", "cat": "pizza", "varianten": {"Classic 32 cm":1050,"XXL 40 cm":1550}},
    74: {"name": "Pizza Truthan Funghi", "cat": "pizza", "varianten": {"Classic 32 cm":1050,"XXL 40 cm":1550}},
    75: {"name": "Pizza Thunfisch", "cat": "pizza", "varianten": {"Classic 32 cm":1150,"XXL 40 cm":1600}},
    76: {"name": "Pizza Rindersalami Spezial", "cat": "pizza", "varianten": {"Classic 32 cm":1050,"XXL 40 cm":1550}},
    77: {"name": "Pizza Vegetarisch", "cat": "pizza", "varianten": {"Classic 32 cm":1050,"XXL 40 cm":1550}},
    78: {"name": "Pizza Quattro Stagioni", "cat": "pizza", "varianten": {"Classic 32 cm":1100,"XXL 40 cm":1600}},
    79: {"name": "Pizza Döner Chicken", "cat": "pizza", "varianten": {"Classic 32 cm":1150,"XXL 40 cm":1550}},
    80: {"name": "Pizza Döner Beef", "cat": "pizza", "varianten": {"Classic 32 cm":1250,"XXL 40 cm":1750}},
    81: {"name": "Pizza Europa", "cat": "pizza", "varianten": {"Classic 32 cm":1150,"XXL 40 cm":1600}},
    82: {"name": "Pizza Toni", "cat": "pizza", "varianten": {"Classic 32 cm":1100,"XXL 40 cm":1600}},
    83: {"name": "Pizza El Chapo", "cat": "pizza", "varianten": {"Classic 32 cm":1150,"XXL 40 cm":1650}},
    84: {"name": "Pizza El Pablo", "cat": "pizza", "varianten": {"Classic 32 cm":1200,"XXL 40 cm":1700}},
    85: {"name": "Pizza Mexicano", "cat": "pizza", "varianten": {"Classic 32 cm":1250,"XXL 40 cm":1750}},
    86: {"name": "Pizzabrötchen Käse", "cat": "pizzabroetchen", "varianten": {"":700}},
    87: {"name": "Pizzabrötchen Chicken - Käse", "cat": "pizzabroetchen", "varianten": {"":850}},
    88: {"name": "Pizzabrötchen Beef - Käse", "cat": "pizzabroetchen", "varianten": {"":950}},
    89: {"name": "Pizzabrötchen Sucuk - Käse", "cat": "pizzabroetchen", "varianten": {"":950}},
    90: {"name": "Pizzabrot mit Oregano & Olivenöl", "cat": "pizzabrot", "varianten": {"32 cm":500,"40 cm":800}},
    91: {"name": "Pizzabrot Knoblauch & Tomatensoße", "cat": "pizzabrot", "varianten": {"32 cm":600,"40 cm":900}},
    92: {"name": "Softdrink 0,33 l", "cat": "getraenke", "varianten": {"":250}},
    93: {"name": "Softdrink 1 l", "cat": "getraenke", "varianten": {"":400}},
    94: {"name": "Ayran 0,25 l", "cat": "getraenke", "varianten": {"":100}},
    95: {"name": "Mineralwasser mit Kohlensäure 0,5 l", "cat": "getraenke", "varianten": {"":200}},
    96: {"name": "Mineralwasser still 0,5 l", "cat": "getraenke", "varianten": {"":200}},
}

PRAEMIEN_EXTRAS = {
    "Fleisch": 150, "Gegrilltes Gemüse": 150,
    "Soße": 100, "Jalapenos": 100, "Knoblauch": 100, "Pilze": 100,
    "Käse": 100, "Oliven": 100, "Salami": 150, "Sucuk": 150,
    "Truthahn": 150, "Ei": 150, "Peperoniwurst": 150, "Thunfisch": 200
}
PRAEMIEN_MENUES = {"Menü L": 400, "Menü XL": 500, "Menü XXL": 650}

